/*
 * Payment API
 * Сервис совершения платежей
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.goncharenko.market.payment.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import java.util.Objects;

/**
 * ApiBalanceGet200Response
 */
@JsonPropertyOrder({
  ApiBalanceGet200Response.JSON_PROPERTY_BALANCE
})
@JsonTypeName("_api_balance_get_200_response")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-05T20:09:49.061497400+03:00[GMT+03:00]", comments = "Generator version: 7.20.0")
public class ApiBalanceGet200Response {
  public static final String JSON_PROPERTY_BALANCE = "balance";
  @jakarta.annotation.Nullable
  private Double balance;

  public ApiBalanceGet200Response() {
  }

  public ApiBalanceGet200Response balance(@jakarta.annotation.Nullable Double balance) {
    
    this.balance = balance;
    return this;
  }

  /**
   * Get balance
   * @return balance
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BALANCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getBalance() {
    return balance;
  }


  @JsonProperty(value = JSON_PROPERTY_BALANCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBalance(@jakarta.annotation.Nullable Double balance) {
    this.balance = balance;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiBalanceGet200Response apiBalanceGet200Response = (ApiBalanceGet200Response) o;
    return Objects.equals(this.balance, apiBalanceGet200Response.balance);
  }

  @Override
  public int hashCode() {
    return Objects.hash(balance);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiBalanceGet200Response {\n");
    sb.append("    balance: ").append(toIndentedString(balance)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

