/*
 * Payment API
 * Сервис совершения платежей
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.goncharenko.market.payment.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.util.Objects;

/**
 * Параметры запроса на списание средств
 */
@JsonPropertyOrder({
  Payment.JSON_PROPERTY_USER_NAME,
  Payment.JSON_PROPERTY_ORDER_AMOUNT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-10T20:48:17.154035700+03:00[GMT+03:00]", comments = "Generator version: 7.20.0")
public class Payment {
  public static final String JSON_PROPERTY_USER_NAME = "userName";
  @jakarta.annotation.Nullable
  private String userName;

  public static final String JSON_PROPERTY_ORDER_AMOUNT = "orderAmount";
  @jakarta.annotation.Nullable
  private Double orderAmount;

  public Payment() {
  }

  public Payment userName(@jakarta.annotation.Nullable String userName) {
    
    this.userName = userName;
    return this;
  }

  /**
   * Get userName
   * @return userName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_USER_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUserName() {
    return userName;
  }


  @JsonProperty(value = JSON_PROPERTY_USER_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUserName(@jakarta.annotation.Nullable String userName) {
    this.userName = userName;
  }

  public Payment orderAmount(@jakarta.annotation.Nullable Double orderAmount) {
    
    this.orderAmount = orderAmount;
    return this;
  }

  /**
   * Get orderAmount
   * @return orderAmount
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ORDER_AMOUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getOrderAmount() {
    return orderAmount;
  }


  @JsonProperty(value = JSON_PROPERTY_ORDER_AMOUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOrderAmount(@jakarta.annotation.Nullable Double orderAmount) {
    this.orderAmount = orderAmount;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Payment payment = (Payment) o;
    return Objects.equals(this.userName, payment.userName) &&
        Objects.equals(this.orderAmount, payment.orderAmount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(userName, orderAmount);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Payment {\n");
    sb.append("    userName: ").append(toIndentedString(userName)).append("\n");
    sb.append("    orderAmount: ").append(toIndentedString(orderAmount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

