/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.20.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package ru.goncharenko.payment.controller;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.annotation.Generated;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.server.ServerWebExchange;
import reactor.core.publisher.Mono;
import ru.goncharenko.payment.response.ApiBalanceGet200Response;
import ru.goncharenko.payment.model.Payment;
import ru.goncharenko.payment.util.ApiUtil;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-03-05T18:56:04.818676400+03:00[GMT+03:00]", comments = "Generator version: 7.20.0")
@Validated
@Tag(name = "api", description = "the api API")
public interface PaymentApi {

    String PATH_API_BALANCE_GET = "/api/balance";
    /**
     * GET /api/balance : Подтверждение баланса пользователя
     * Получить подтверждение, что на балансе пользователя достаточно средств для осуществления покупки
     *
     * @param userName Логин пользователя (required)
     * @return Баланс счета получен (status code 200)
     */
    @Operation(
        operationId = "apiBalanceGet",
        summary = "Подтверждение баланса пользователя",
        description = "Получить подтверждение, что на балансе пользователя достаточно средств для осуществления покупки",
        responses = {
            @ApiResponse(responseCode = "200", description = "Баланс счета получен", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiBalanceGet200Response.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = PaymentApi.PATH_API_BALANCE_GET,
        produces = { "application/json" }
    )
    default Mono<ResponseEntity<ApiBalanceGet200Response>> apiBalanceGet(
        @NotNull @Parameter(name = "userName", description = "Логин пользователя", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "userName", required = true) String userName,
        @Parameter(hidden = true) final ServerWebExchange exchange
    ) {
        Mono<Void> result = Mono.empty();
        exchange.getResponse().setStatusCode(HttpStatus.NOT_IMPLEMENTED);
        for (MediaType mediaType : exchange.getRequest().getHeaders().getAccept()) {
            if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                String exampleString = "{ \"balance\" : 238731.17 }";
                result = ApiUtil.getExampleResponse(exchange, MediaType.valueOf("application/json"), exampleString);
                break;
            }
        }
        return result.then(Mono.empty());

    }


    String PATH_API_BALANCE_POST = "/api/balance";
    /**
     * POST /api/balance : Осуществление платежа
     * Осуществление платежа
     *
     * @param payment  (required)
     * @return Платеж осуществлен (status code 200)
     */
    @Operation(
        operationId = "apiBalancePost",
        summary = "Осуществление платежа",
        description = "Осуществление платежа",
        responses = {
            @ApiResponse(responseCode = "200", description = "Платеж осуществлен")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = PaymentApi.PATH_API_BALANCE_POST,
        consumes = { "application/json" }
    )
    default Mono<ResponseEntity<String>> apiBalancePost(
        @Parameter(name = "Payment", description = "", required = true) @Valid @RequestBody Payment payment,
        @Parameter(hidden = true) final ServerWebExchange exchange
    ) {
        Mono<Void> result = Mono.empty();
        exchange.getResponse().setStatusCode(HttpStatus.NOT_IMPLEMENTED);
        return result.then(Mono.empty());

    }

}
