spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres?currentSchema=market
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8090/realms/master # Адрес сервера авторизации для получения токена
        registration:
          market: # Описание клиента OAuth2
            provider: keycloak
            authorizationGrantType: client_credentials
            client-id: ${MARKET_CLIENT_ID}
            client-secret: ${MARKET_CLIENT_SECRET}
            scope: profile
            clientAuthenticationMethod: client_secret_post # Способ передачи секрета

application:
  webClient:
    baseUrl: http://payment-service:8081
