services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_db_dev
    restart:  no
    environment:
      POSTGRES_DB: market
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:      