services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_market_db
    restart:  no
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis-container
    restart: no
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  payment-service:
    build: ./payment-service
    image: payment-service:latest
    container_name: payment-service
    restart: no
    ports:
      - "8081:8081"
    environment:
      # Liquibase переменные
      SPRING_LIQUIBASE_URL: jdbc:postgresql://postgres:5432/postgres?currentSchema=payment
      SPRING_LIQUIBASE_USERNAME: postgres
      SPRING_LIQUIBASE_PASSWORD: password
      # Реактивное подключение к PostgreSQL
      SPRING_R2DBC_URL: r2dbc:postgresql://postgres:5432/postgres?currentSchema=payment
      SPRING_R2DBC_USERNAME: postgres
      SPRING_R2DBC_PASSWORD: password
    depends_on:
      - postgres
      - redis

  online-store:
    build: ./online-store
    image: online-store:latest
    container_name: online-store
    restart: no
    ports:
      - "8080:8080"
    environment:
      # Реактивное подключение к PostgreSQL
      SPRING_R2DBC_URL: r2dbc:postgresql://postgres:5432/postgres?currentSchema=payment
      SPRING_R2DBC_USERNAME: postgres
      SPRING_R2DBC_PASSWORD: password
      # Подключение к Redis
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379

volumes:
  postgres_data:
  redis_data:
