spring:
  application:
    name: market
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=market
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always
