spring:
  application:
    name: payment
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres?currentSchema=payment
    username: postgres
    password: password
  liquibase:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=payment
    user: postgres
    password: password
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: payment
    liquibase-schema: public
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
      continue-on-error: true

server:
  port: 8081